<div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
        <form method="POST">
            <?php
            if (isset($error)) {
                echo "<div class='alert alert-danger'>{$error}</div>";
            }
            ?>
            <div class="form-group">
                <label for="login">Entrar</label>
                <input type="text" name="login" placeholder="Login (just)" class="form-control">
            </div>

            <div class="form-group">
                <input type="password" name="password" placeholder="Senha (just)" class="form-control">
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-info">Login</button>
            </div>
        </form>
    </div>
</div>
