<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th width="128">Opções</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($posts as $post) {
    ?>
        <tr data-id="post<?php echo $post->getId();?>">
            <td><?php echo $post->getTitle();?></td>
            <td class="btn-group">
                <a href="/admin/posts/edit/<?php echo $post->getId();?>/" class="btn btn-info"><i class="glyphicon glyphicon-pencil"></i></a>
                <a href="#" class="delete btn btn-danger" data-id="<?php echo $post->getId();?>"><i class="glyphicon glyphicon-trash"></i></a>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<script>
$(function() {
    $('.delete').on('click', function(e) {
        e.preventDefault();
        var id = $(this).attr('data-id');
        if (confirm('Deseja realmente apagar este post?')) {
            $.ajax({
                url: '/admin/posts/delete/' + id + '/',
                type: 'GET',
                dataType: 'JSON',
                beforeSend: function() {
                    $('body').css('cursor', 'progress');
                },
                complete: function() {
                    $('body').css('cursor', '');
                },
                success: function(data) {
                    alert(data.result);
                    if (! data.error) {
                        $('tr[data-id="post' + id + '"]').remove();
                    }
                },
                error: function() {
                    alert('Ocorreu um erro ao tentar realizar esta ação. Tente mais tarde.');
                }
            });
        }
    });
});
</script>
