<div class="row">
    <div class="col-xs-12 col-sm-8">
        <article>
            <h1><?php echo $post->getTitle();?></h1>
            <?php echo $post->getBody();?>
        </article>
    </div>

    <div class="col-xs-12 col-sm-4 all-posts">
        <h4>Veja mais</h4>
        <ul class="list-group">
            <?php
            foreach ($posts as $post) {
            ?>
            <li class="list-group-item">
                <a href="/noticias/<?php echo $post->getSlug();?>/">
                    <?php echo $post->getTitle();?>
                </a>
            </li>
            <?php
            }
            ?>
        </ul>
    </div>
</div>
